# Makefile for GNU Make.
# $Id: GNUmakefile 21 2005-01-23 00:03:02Z hex $

include ../../Makedefs.faerion.include

TARGET = library.static
PROG   = rascal.a
SRCS   = $(wildcard *.cc resolver/*.cc)
DEFS  += BUILD_RASCAL RASCAL_HELPERS

include ../../Makedefs.faerion
