import os
Import('env', 'fnd')

env.Append(tools = ['mingw'], CPPDEFINES = ['BUILD_RASCAL'], CPPPATH = ['../common/util'])
objs = []

for item in fnd.listFiles(['.', '../common'], r'^.*(\.cc)$'):
	fname, ext = os.path.splitext(item)
	objs.append(env.SharedObject(fname + '.os', item))

env.SharedLibrary('rascal', objs)
