import os
Import('env', 'fae')

envbsd = env.Copy()
envbsd.Append(
	CPPDEFINES = ['BUILD_RASCAL', ('funs', 'librans')],
	category = 'core',
	CPPPATH = '../common/util')

envbsd.Append(SHLINKFLAGS = ['-dylib_compatibility_version=1', '-dylib_current_version=1', '-dylib_install_name=' + env['instdir'] + '/librascal.dylib'])

fae.ilibs = envbsd.SharedLibrary('rascal', fae.compile(envbsd, ['.', '../common']))

# $Id$
# vim:ts=4:sts=4:sw=4:noet:syntax=python
