import os
Import('env', 'fae')

envbsd = env.Copy()
envbsd.Append(CPPDEFINES = ['BUILD_RASCAL', ('funs', 'librans')], category = 'core', CPPPATH = '../common/util')
envbsd.SharedLibrary('rascal', fae.compile(envbsd, ['.', '../common']))

# $Id$
# vim:ts=4:sts=4:sw=4:noet:syntax=python
