import os
Import('env', 'fnd')

envbsd = env.Copy()
envbsd.Append(CPPDEFINES = ['BUILD_RASCAL', ('funs', 'librans')], CPPPATH = '../common/util')
objs = []

for item in fnd.listFiles(['.', '../common'], r'^.*(\.cc)$'):
	fname, ext = os.path.splitext(item)
	objs.append(envbsd.SharedObject(fname + '.os', item))

envbsd.SharedLibrary('rascal', objs)

# $Id$
# vim:ts=2:sts=2:sw=2:noet:syntax=python
