import os
Import('env', 'fae')

envsam = env.Copy()
envsam.Append(
	CPPDEFINES = [('funs', 'rasamples')],
	category = 'smp',
	CPPPATH = ['../common/util', env['instdir'] + '/include'],
	LIBPATH = [env['instdir'] + '/lib'],
	LIBS = ['rascal'])

for sub in ['raconn', 'raconns', 'raflood', 'rahost', 'ralc', 'rasvc']:
	fae.ibins.append(envsam.Program(sub + '/' + sub, fae.compile(envsam, ['../common/util', sub])))

# $Id$
# vim:ts=4:sts=4:sw=4:noet:syntax=python
