import os
Import('env', 'fnd')

senv = env.Copy()
senv.Append(CPPPATH = ['../common/util', '..'], LIBPATH = '#/../../' + env['LIBARCH'], LIBS = 'rascal')

src = fnd.listFiles(['../common/util'], r'^.*(\.cc)$')

senv.Program('raconn', src + ['01-raconn/raconn.cc'])
senv.Program('raconns', src + ['02-raconns/test-02.cc'])
senv.Program('rahost', src + ['04-rahost/rahost.cc'])
